name: tests

on: [push]

jobs:
  build:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-version: [8.1, 8.2]
        include:
          - php-version: [8.3, 8.4]
            flags: "--ignore-platform-req=php"
            stability: prefer-stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug

      - name: Install Composer Dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: composer update --no-interaction --no-progress --no-progress ${{ matrix.flags }}

      - name: Install NPM Dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: npm install

      - name: Setting up the application
        run: |
          php artisan config:clear
          npm run dev

      - name: Execute Tests
        run: ./vendor/bin/phpunit
